---
- name: Delete infra components
  hosts: web
  tasks:
    - name: Uninstall git
      yum:
         name: git
         state: absent
      when:
       - ansible_os_family == "RedHat"
       - ansible_distribution == "CentOS"

- name: Uninstall java component
  hosts: web
  tasks:
    - name: Uninstall java
      yum:
         name: java-11-openjdk-headless
         state: absent
