---
- name: Delete git components
  hosts: webservers
  become: yes
  tasks:
    - name: Uninstall git
      apt:
         name: git
         state: absent
      when:
       - ansible_os_family == "Debian"
       - ansible_distribution == "Ubuntu"
 
- name: Install infra components
  hosts: webservers
  become: yes
  tasks:
    - name: Install system updates for Ubuntu
      apt:
        name: '*'
        state: latest
        update_cache: yes
        #cache_valid_time: 3600
      when:
       - ansible_os_family == "Debian"
       - ansible_distribution == "Ubuntu"
 
    - name: Install git
      apt:
         name: git
         state: present