---
- name: Install infra components
  hosts: web
  tasks:
    - name: Install system updates for centos
      yum:
        name: '*'
        state: latest
        update_cache: yes
        #cache_valid_time: 3600
      when:
       - ansible_os_family == "RedHat"
       - ansible_distribution == "CentOS" 

    - name: Install git
      yum:
         name: git
         state: present

    - name: Install java
      yum:
         name: java-11-openjdk
         state: present
